# Generated by Django 4.1.1 on 2022-09-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spa',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
